export const US_STATES = [
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
] as const;

export type USState = (typeof US_STATES)[number];

// Average peak sun hours by state (placeholder values - update with real data)
export const PEAK_SUN_HOURS: Record<string, number> = {
  Alabama: 4.5,
  Alaska: 3.0,
  Arizona: 6.5,
  Arkansas: 4.7,
  California: 5.8,
  Colorado: 5.5,
  Connecticut: 4.0,
  Delaware: 4.2,
  Florida: 5.4,
  Georgia: 4.8,
  Hawaii: 5.5,
  Idaho: 4.9,
  Illinois: 4.2,
  Indiana: 4.1,
  Iowa: 4.4,
  Kansas: 5.0,
  Kentucky: 4.2,
  Louisiana: 4.8,
  Maine: 4.0,
  Maryland: 4.3,
  Massachusetts: 4.0,
  Michigan: 3.8,
  Minnesota: 4.2,
  Mississippi: 4.7,
  Missouri: 4.5,
  Montana: 4.6,
  Nebraska: 4.8,
  Nevada: 6.2,
  "New Hampshire": 4.0,
  "New Jersey": 4.2,
  "New Mexico": 6.4,
  "New York": 3.9,
  "North Carolina": 4.6,
  "North Dakota": 4.4,
  Ohio: 3.9,
  Oklahoma: 5.0,
  Oregon: 4.2,
  Pennsylvania: 3.9,
  "Rhode Island": 4.0,
  "South Carolina": 4.8,
  "South Dakota": 4.6,
  Tennessee: 4.4,
  Texas: 5.5,
  Utah: 5.6,
  Vermont: 3.8,
  Virginia: 4.3,
  Washington: 3.8,
  "West Virginia": 3.9,
  Wisconsin: 4.0,
  Wyoming: 5.0,
};

// Placeholder calculation constants - update with real values later
export const CALC_CONSTANTS = {
  ANNUAL_ELECTRICITY_INFLATION: 0.03, // 3% annual increase
  COST_PER_WATT: 3, // USD per watt installed
  SYSTEM_DEGRADATION: 0.005, // 0.5% annual degradation
  PROJECTION_YEARS: 25,
  PANEL_WATTAGE: 400, // watts per panel
  AVERAGE_UTILITY_RATE: 0.15, // USD per kWh (placeholder)
};
